'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {foods,foodById,makeRound,evaluate,metrics,values,sanitizeCut,type Cut} from './model';
import './pizza.css';
const Scene=dynamic(()=>import('./PizzaScene'),{ssr:false,loading:()=> <div className="pz-scene pz-load">準備烘焙工作桌…</div>});
const initial:Cut={angle:0,offset:0};
export default function PizzaLab(){
 const [level,setLevel]=useState(0),[seed,setSeed]=useState(431),[cut,setCut]=useState<Cut>(initial),[phase,setPhase]=useState<'edit'|'cutting'|'result'>('edit'),[orbit,setOrbit]=useState(false),[top,setTop]=useState(false),[viewNonce,setViewNonce]=useState(0),[selected,setSelected]=useState<string|null>(null),[attempts,setAttempts]=useState<{score:number;cut:Cut}[]>([]),[best,setBest]=useState<number[]>([0,0,0]),[sound,setSound]=useState(true),[hint,setHint]=useState(false),[showInfo,setShowInfo]=useState(false),[done,setDone]=useState(false);
 const round=useMemo(()=>makeRound(seed,level),[seed,level]),result=useMemo(()=>evaluate(round,cut),[round,cut]);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null),audio=useRef<AudioContext|null>(null),bench=useRef<HTMLElement>(null),report=useRef<HTMLDivElement>(null),lock=useRef(false),finale=useRef<HTMLElement>(null),soundMix=useRef<GainNode|null>(null),stage=useRef<HTMLDivElement>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);audio.current?.close();},[]);
 const menu=[...new Set(round.toppings.map(t=>t.food))];
 const food=selected?foodById[selected]:null,portion=selected?round.toppings.find(t=>t.food===selected)?.grams||0:0;
 function chime(){if(!sound)return;try{
  const ac=audio.current??(audio.current=new AudioContext());void ac.resume();
  const mix=ac.createGain();mix.gain.value=.55;mix.connect(ac.destination);soundMix.current=mix;
  // Filtered noise follows the rolling cutter; a short crunch and bell mark separation.
  const buffer=ac.createBuffer(1,Math.ceil(ac.sampleRate*.75),ac.sampleRate),data=buffer.getChannelData(0);
  for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(.65+.35*Math.sin(i/ac.sampleRate*95));
  const noise=ac.createBufferSource(),filter=ac.createBiquadFilter(),gain=ac.createGain(),now=ac.currentTime;
  noise.buffer=buffer;filter.type='bandpass';filter.frequency.setValueAtTime(1800,now);filter.frequency.exponentialRampToValueAtTime(520,now+.65);filter.Q.value=.7;
  gain.gain.setValueAtTime(.001,now);gain.gain.linearRampToValueAtTime(.3,now+.06);gain.gain.setValueAtTime(.18,now+.5);gain.gain.exponentialRampToValueAtTime(.001,now+.74);
  noise.connect(filter).connect(gain).connect(mix);noise.start();noise.onended=()=>{noise.disconnect();filter.disconnect();gain.disconnect();};
  [740,988,1480].forEach((f,i)=>{const o=ac.createOscillator(),g=ac.createGain(),start=now+.72+i*.085;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.001,start);g.gain.linearRampToValueAtTime(.11,start+.012);g.gain.exponentialRampToValueAtTime(.001,start+.32);o.connect(g).connect(mix);o.start(start);o.stop(start+.34);o.onended=()=>{o.disconnect();g.disconnect();if(i===2)mix.disconnect();};});
 }catch{/* Sound is optional when the device blocks audio. */}}
 function adjust(c:Cut){if(lock.current||phase!=='edit')return;setCut(sanitizeCut(c));setHint(false);}
 function serve(){if(lock.current||phase!=='edit')return;lock.current=true;setPhase('cutting');setOrbit(false);stage.current?.scrollIntoView({block:'start',behavior:'instant'});chime();const score=result.score,chosen={...cut};timer.current=setTimeout(()=>{setPhase('result');setOrbit(true);setAttempts(a=>[...a,{score,cut:chosen}]);setBest(b=>b.map((v,i)=>i===level?Math.max(v,score):v));lock.current=false;requestAnimationFrame(()=>report.current?.scrollIntoView({block:'nearest',behavior:'smooth'}));},matchMedia('(prefers-reduced-motion: reduce)').matches?100:1500);}
 function retry(){setPhase('edit');setOrbit(false);setHint(false);setDone(false);requestAnimationFrame(()=>bench.current?.scrollIntoView({block:'start',behavior:'instant'}));}
 function next(){if(level===2){setDone(true);requestAnimationFrame(()=>finale.current?.scrollIntoView({block:'start',behavior:'smooth'}));return;}setLevel(l=>l+1);setSeed(s=>s+109);setCut(initial);setPhase('edit');setOrbit(false);setSelected(null);setHint(false);setAttempts([]);requestAnimationFrame(()=>bench.current?.scrollIntoView({block:'start',behavior:'instant'}));}
 const display=(value:number,id:string)=>id==='carbon'||id==='energy'?value.toFixed(1):value.toFixed(2);
 return <main className="pz-page">
  <nav className="pz-nav"><Link href="/package/6.6-III/">← 返回教案</Link><span>主題六 · 永續飲食</span><label><input type="checkbox" checked={sound} onChange={e=>{setSound(e.target.checked);if(!e.target.checked&&soundMix.current)soundMix.current.gain.value=0;}}/> 音效</label></nav>
  <header className="pz-header"><div><p className="pz-eyebrow">THE SHARED TABLE / 06</p><h1>一人一半，怎麼切？</h1><p>同一張披薩，讓兩份的碳足跡與營養分配都接近。</p></div><button onClick={()=>setShowInfo(!showInfo)} aria-expanded={showInfo}>玩法與計分 {showInfo?'−':'＋'}</button></header>
  {showInfo&&<section className="pz-help"><h2>先觀察配料，再決定切線。</h2><p>你要把披薩分給兩位朋友。切成同樣大小，不一定分到相近的配料；碳足跡相近，也不一定熱量和蛋白質相近。試著找到兼顧兩者的一刀。</p><ol><li>在披薩上拖出直線，或用下方角度、位置滑桿調整。</li><li>按「切開看看」，觀察兩份分離。</li><li>比較 A、B 兩份的數值；合起來重切，保留本張最高分。</li></ol><p>平衡度 ＝ 100 ×（1 − 兩份差值 ÷ 兩份總和）。營養分配取熱量、蛋白質、脂肪、碳水四項中最低分；總分再取碳足跡、營養與餅皮面積三項最低分。三項都達 85 分即通關，閱讀與重試不扣分。</p></section>}
  <section className="pz-workbench" ref={bench}>
   <div className="pz-mission"><div><span>第 0{level+1} 張 / 03 · {['先找公平的一刀','多一點配料，多一點取捨','最後挑戰：兼顧每一項'][level]}</span><h2>{phase==='edit'?'分成兩份，同時照顧碳足跡與營養':phase==='cutting'?'切開中，看看配料去了哪一份…':result.passed?'這一刀，三項都達標了！':'已分成兩份，看看哪一項差最多'}</h2></div><div className="pz-badge"><b>{round.toppings.length}</b><small>片配料</small></div></div>
   <ol className="pz-steps"><li className={phase==='edit'?'current':''}><b>1</b>觀察、調整切線</li><li className={phase==='cutting'?'current':''}><b>2</b>切開看看</li><li className={phase==='result'?'current':''}><b>3</b>比較、再切一次</li></ol>
   <div className="pz-layout"><div className="pz-stage" ref={stage}><div className="pz-toolbar"><div><button aria-pressed={!orbit} disabled={phase!=='edit'} onClick={()=>setOrbit(false)}>畫切線</button><button aria-pressed={orbit} disabled={phase==='cutting'} onClick={()=>setOrbit(true)}>轉動觀察</button></div><div><button aria-pressed={top} disabled={phase==='cutting'} onClick={()=>{setTop(!top);setViewNonce(n=>n+1);}}>{top?'立體視角':'俯視看清楚'}</button><button disabled={phase==='cutting'} onClick={()=>{setTop(false);setViewNonce(n=>n+1);}}>回正</button></div></div>
    <Scene round={round} cut={cut} separated={phase!=='edit'} orbit={orbit} top={top} viewNonce={viewNonce} onCut={adjust} onInspect={setSelected}/>
    <div className="pz-adjust"><div className="pz-cut-label"><span><i className="pz-a"/> A 份</span><b>一條切線，分開食材的影響</b><span><i className="pz-b"/> B 份</span></div><div className="pz-sliders"><label>切線角度 <strong>{Math.round(cut.angle)}°</strong><input type="range" aria-label="切線角度" min="0" max="179" step="1" value={cut.angle} disabled={phase!=='edit'} onChange={e=>adjust({...cut,angle:Number(e.target.value)})}/></label><label>切線位置 <strong>{Math.abs(cut.offset)<.025?'通過中心':`${cut.offset>0?'+':''}${cut.offset.toFixed(2)}`}</strong><input type="range" aria-label="切線位置" min="-1.65" max="1.65" step=".05" value={cut.offset} disabled={phase!=='edit'} onChange={e=>adjust({...cut,offset:Number(e.target.value)})}/></label></div>
    <div className="pz-action-row">{phase==='edit'?<><button className="pz-primary" onClick={serve}>切開看看 →</button><button onClick={()=>adjust(initial)}>切線置中</button></>:phase==='cutting'?<button className="pz-primary" disabled>正在切開披薩…</button>:<><button className="pz-primary" onClick={retry}>合起來重切 ↺</button><button onClick={next}>{level===2?'看三張成果':'換下一張'} →</button></>}</div>
    {phase==='edit'&&<p className="pz-action-hint">{orbit?'目前是觀察模式。按「畫切線」，或直接調整滑桿。':'在餅面按住拖曳即可畫線；調整完再按「切開看看」。'}</p>}
    </div></div>
    <aside className="pz-report" ref={report}><p className="pz-eyebrow">TWO SHARES, ONE PIZZA</p><h3>{phase==='result'?'這一刀的分配結果':'切開後揭曉分配'}</h3><div className="pz-score"><span>{phase==='result'?Math.round(result.score):'—'}</span><div><b>三項兼顧分數</b><small>取最低項，避免顧此失彼</small></div></div>
     <div className="pz-goals">{[['配料碳足跡',result.scores.carbon],['配料營養分配',result.nutrition],['餅皮面積',result.areaScore]].map(([label,value])=><div key={label}><span>{label}</span><b>{phase==='result'?`${Math.round(Number(value))} / 100`:'等待切開'}</b><progress max={100} value={phase==='result'?Number(value):0}/></div>)}</div>
     {phase==='result'?<><div className="pz-table-head"><span>每份配料估算</span><b>A 份</b><b>B 份</b></div>{metrics.map(m=>{const total=result.a[m.id]+result.b[m.id],a=total?result.a[m.id]/total:.5;return <div className="pz-metric" key={m.id}><div><span>{m.name}<small>{m.unit}</small></span><b>{display(result.a[m.id],m.id)}</b><b>{display(result.b[m.id],m.id)}</b></div><div className="pz-bar"><span style={{width:`${a*100}%`}}/><i/></div></div>;})}<p className={`pz-verdict ${result.passed?'success':''}`} role="status">{result.passed?'兩份的配料影響與餅皮面積都接近，可以換下一張挑戰。':'先找分數最低的一項，再看造成差距的配料在哪一側。試著旋轉切線或稍微移開中心。'}</p></>:<div className="pz-empty-result"><span>Ａ ── Ｂ</span><p>目標是三項都達 85 分。<br/>先觀察配料，不必急著下刀。</p><small>同樣面積，不一定有同樣的碳足跡與營養。</small></div>}
     <p className="pz-scope-note">數值只計配料；餅皮、底醬與烘焙未納入。營養分配接近不等於完整健康餐，切法也不會降低整張披薩的總碳足跡。</p>
    </aside></div>
  </section>
  <section className="pz-pantry"><div className="pz-pantry-head"><div><p className="pz-eyebrow">KNOW YOUR TOPPINGS</p><h2>先認識這張披薩的配料</h2></div><span>點名稱或模型查看資料 · 每種各有兩片</span></div><div className="pz-foods">{menu.map(id=><button key={id} aria-pressed={selected===id} onClick={()=>setSelected(selected===id?null:id)}><i style={{background:`#${foodById[id].color.toString(16).padStart(6,'0')}`}}/>{foodById[id].name}<small>{round.toppings.find(t=>t.food===id)!.grams} g / 片</small></button>)}</div>{food&&<div className="pz-food-card"><b>{food.name} · 每片 {portion} g</b><span>碳足跡 {values(food,portion).carbon.toFixed(1)} g CO₂e</span><span>熱量 {values(food,portion).energy.toFixed(1)} kcal</span><span>蛋白質 {values(food,portion).protein.toFixed(2)} g</span><span>脂肪 {values(food,portion).fat.toFixed(2)} g</span><span>碳水 {values(food,portion).carb.toFixed(2)} g</span></div>}</section>
  <div className="pz-session"><p>本張試切 <b>{attempts.length}</b> 次 · 最佳 <b>{Math.round(best[level])}</b> 分</p><button disabled={phase==='cutting'} onClick={()=>setHint(!hint)} aria-expanded={hint}>{hint?'收起思考提示':'卡住了？看思考提示'}</button></div>
  {hint&&<div className="pz-hint"><b>不要只追求大小一樣。</b><p>先找成對、份量相同的配料，讓它們分到不同側。碳足跡較高的配料可能左右碳分數，起司、肉類也會影響脂肪與蛋白質。切過配料時，系統會依覆蓋面積分攤。</p><button disabled={phase!=='edit'} onClick={()=>adjust({angle:round.solution,offset:0})}>示範一條可兼顧的切線</button><small>示範後仍需按「切開看看」。可重試，不扣分。</small></div>}
  {attempts.length>0&&<details className="pz-history"><summary>這張的試切紀錄</summary><ol>{attempts.map((a,i)=><li key={i}>第 {i+1} 刀：{a.cut.angle.toFixed(0)}°、位置 {a.cut.offset.toFixed(2)} → {a.score.toFixed(0)} 分<button disabled={phase!=='edit'} onClick={()=>adjust(a.cut)}>套用這條切線</button></li>)}</ol></details>}
  {done&&<section className="pz-finale" ref={finale}><p className="pz-eyebrow">THE TABLE IS SET</p><h2>三張披薩，你怎麼兼顧？</h2><div>{best.map((s,i)=><p key={i}><span>第 {i+1} 張</span><b>{Math.round(s)}</b><small>{s>=85?'三項達標':'可以再試試'}</small></p>)}</div><p>想一想：兩份碳足跡一樣，為什麼不代表營養也一樣？如果想降低整張披薩的碳足跡，還需要改變哪些食材或份量？</p><button className="pz-primary" onClick={()=>{setLevel(0);setSeed(s=>s+317);setBest([0,0,0]);setAttempts([]);setDone(false);setCut(initial);setPhase('edit');setOrbit(false);setSelected(null);requestAnimationFrame(()=>bench.current?.scrollIntoView({block:'start',behavior:'instant'}));}}>再烤三張新的 →</button></section>}
  <details className="pz-teacher"><summary>教師備註・計算方式、來源與替代操作</summary><p>改編自使用者提供的 balance 專案披薩切分玩法，連結 6.6-III 永續飲食。學習重點是同時觀察配料碳足跡與營養素分配，並非提供個人飲食建議。遊戲假設兩位朋友需要相近份量；真實需求會因人而異。</p><p>來源為參考專案 pizzacut.csv 的固定資料快照（丹麥市場資料），不代表臺灣所有同名食材的現行數值。原碳係數 kg CO₂e/kg × 食材克數得到 g CO₂e；kJ/100 g 換成 kcal 時除以 4.184。其餘營養素依 g/100 g 換算。資料包含生、熟與加工品差異，名稱依 CSV 標示；模型外觀僅作教學辨識。</p><p>餅皮、底醬與烘焙未計入數值，另用餅皮面積平衡防止切出極小份。配料以放大後的圓形足跡、均勻密度近似，切到配料時按圓面積比例分攤；實際模型切面只作視覺呈現。分成 A、B 後各項總量守恆，重新切分不減少總排放。擺放保留一條可達 100 分的切線，不把無解盤面交給學生。</p><div className="pz-source-table"><table><thead><tr><th>食材</th><th>CSV 列識別</th><th>kg CO₂e/kg</th><th>kJ/100 g</th></tr></thead><tbody>{foods.map(f=><tr key={f.id}><td>{f.name}</td><td>{f.sourceId}</td><td>{f.co2}</td><td>{f.energy}</td></tr>)}</tbody></table></div><p>可用滑桿或鍵盤調整角度及位置；支援減少動畫偏好。下表座標以餅心為原點，可在無 3D 時輔助判斷。分數只保留於目前頁面，不收集姓名。</p><div className="pz-source-table"><table><thead><tr><th>配料</th><th>x</th><th>z</th><th>g</th></tr></thead><tbody>{round.toppings.map(t=><tr key={t.id}><td>{foodById[t.food].name}</td><td>{t.x.toFixed(2)}</td><td>{t.z.toFixed(2)}</td><td>{t.grams}</td></tr>)}</tbody></table></div></details>
 </main>;
}
