import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyAnimals,emptyCrossing,simulateAnimals,animalCost,cleanAnimals,ANIMAL_BUDGET} from './animals.ts';
import {simulateHeat,temperature,cleanTrees,plantingSites,HEAT_THRESHOLD,ENERGY_MAX,homes,CENTER,PER_HOME,TREE_LIMIT} from './heat.ts';
const tunnel=()=>({...emptyCrossing(),kind:'tunnel',guide:true,wide:true});
const both=[tunnel(),tunnel()];
const cool=[{x:5,z:3},{x:7,z:5}];
function conserved(r,total){assert.equal(r.travelers.length,total);assert.equal(new Set(r.travelers.map(p=>p.id)).size,total);assert.equal(Object.values(r.counts).reduce((a,b)=>a+b,0),total);assert.equal(r.success,r.travelers.filter(p=>p.outcome==='抵達'||p.outcome==='安全返家').length);for(const p of r.travelers){assert.notEqual(p.outcome,'途中');p.samples.forEach((s,i)=>{assert.ok(Number.isFinite(s.x+s.y+s.z+s.t));if(i)assert.ok(s.t>=p.samples[i-1].t,'chronological replay');});}}
test('Every departing animal has one terminal outcome; trials are deterministic',()=>{for(const d of [emptyAnimals(),both]){const a=simulateAnimals(d);conserved(a,24);assert.deepEqual(a,simulateAnimals(d));assert.ok(a.duration<=42);}});
test('Connected guided wide tunnels eliminate surface collisions within the material budget',()=>{assert.equal(animalCost(both),ANIMAL_BUDGET);const base=simulateAnimals(emptyAnimals()),good=simulateAnimals(both);assert.ok(base.counts['路殺']>0);assert.equal(good.success,24);assert.equal(good.counts['路殺']??0,0);assert.ok(good.travelers.every(p=>p.samples.some(s=>s.y<0)));assert.equal(simulateAnimals(both,1).success,24);});
test('Bridge height continuity and edge protection have causal consequences',()=>{const bridge={...emptyCrossing(),kind:'bridge',entry:true,exit:true,guide:true};const bad=simulateAnimals([bridge,emptyCrossing()]);assert.ok(bad.counts['跌落']>0);const noEntry=simulateAnimals([{...bridge,entry:false},emptyCrossing()]);assert.ok(noEntry.counts['受困／逾時']>0);const noExit=simulateAnimals([{...bridge,exit:false,guard:true},emptyCrossing()]);assert.ok(noExit.travelers.some(p=>p.detail.includes('橋尾')));const safe=simulateAnimals([{...bridge,guard:true,wide:true},emptyCrossing()]);assert.equal(safe.counts['跌落']??0,0);assert.ok(safe.success>bad.success);conserved(bad,24);conserved(noEntry,24);});
test('Over-budget engineering and invalid tree locations cannot bypass limits',()=>{assert.deepEqual(cleanAnimals([{...both[0],kind:'bridge',entry:true,exit:true,guard:true},both[1]]),emptyAnimals());const clean=cleanTrees([{x:3,z:3},{x:-1,z:0},...plantingSites,...plantingSites]);assert.equal(clean.length,TREE_LIMIT);assert.equal(new Set(clean.map(t=>`${t.x},${t.z}`)).size,TREE_LIMIT);});
test('Trees cool the intended neighborhood once; selection improves complete return journeys',()=>{const t={x:7,z:5};assert.equal(temperature(7,4,[t]),temperature(7,4,[])-6);assert.equal(temperature(4,0,[t]),temperature(4,0,[]));assert.equal(temperature(7,4,[t,t]),temperature(7,4,[t]));const before=simulateHeat([]),after=simulateHeat(cool);conserved(before,12);conserved(after,12);assert.ok(before.success<after.success);assert.equal(after.success,12);assert.ok(before.travelers.some(p=>p.outcome==='回程耗盡'&&p.completed===p.required));assert.deepEqual(after,simulateHeat(cool));});
test('Energy changes only on entering a tile, caps at 10, stops at zero; KPI requires errands plus home',()=>{for(const trees of [[],cool]){const r=simulateHeat(trees);for(const p of r.travelers){for(let i=1;i<p.samples.length;i++){const a=p.samples[i-1],b=p.samples[i],moved=a.x!==b.x||a.z!==b.z;const expected=moved?Math.min(ENERGY_MAX,a.energy+(temperature(b.x+CENTER,b.z+CENTER,trees)>=HEAT_THRESHOLD?-1:1)):a.energy;assert.equal(b.energy,expected);assert.ok(b.energy>=0&&b.energy<=10);if(b.energy===0)assert.equal(i,p.samples.length-1);}if(p.outcome==='安全返家'){assert.equal(p.completed,p.required);assert.ok(p.energy>=1);const home=homes[Math.floor(p.id/PER_HOME)],last=p.samples.at(-1);assert.equal(last.x,home.x-CENTER);assert.equal(last.z,home.z-CENTER);}else assert.equal(p.energy,0);}}});

test('Simple map tells the same story as the simulation: west has shade, east needs help',()=>{const base=simulateHeat([]);assert.equal(base.travelers.filter(p=>p.origin==='西側住宅'&&p.outcome==='安全返家').length,6);assert.equal(base.travelers.filter(p=>p.origin==='東側住宅'&&p.outcome==='安全返家').length,0);assert.ok(base.travelers.every(p=>p.required===1));assert.equal(plantingSites.length,6);assert.equal(simulateHeat([{x:1,z:5}]).success,base.success,'extra west shade alone cannot fix east journeys');});
