'use client';
import {useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {useGameEvents} from '@/lib/useGameEvents';

import {topics,itemByKey,makeRound,fresh,act,found,finished,type Topic,type Category,type Game,type Action} from './model';
import './carbon-match.css';
const Scene=dynamic(()=>import('./MatchScene'),{ssr:false,loading:()=> <div className="cm-canvas cm-scene-status">正在準備物件…</div>});
const topicGroups:{label:string;topics:Topic[]}[]=[
 {label:'學校直接排放（範疇一）',topics:['combustion','mobile','fugitive','scope1']},
 {label:'買來的電（範疇二）',topics:['electricity']},
 {label:'學校間接造成的排放',topics:['commute','water','waste']},
 {label:'加分關',topics:['reduction']},
];
const topicOrder:Topic[]=topicGroups.flatMap(g=>g.topics);
const captions:Record<Category,string>={combustion:'校內燃燒',mobile:'車輛燃燒',fugitive:'氣體逸散',electricity:'外購電力',commute:'員工通勤',water:'外購水力',waste:'垃圾處理',reduction:'減碳與吸碳',toy:'一般玩具',exempt:'不必計入的通勤'};
const quizzes={
 ac:{q:'換個情境：同一台冷氣，用電和冷媒逸散怎麼分？',options:['用電是範疇二；冷媒逸散是範疇一','都是範疇二，因為冷氣要插電','都是範疇一，因為冷氣在校內'],ok:'正確！同一個設備可以有不同排放活動，必須分開看。',retry:'再想想：用電的排放發生在供電端；冷媒逸散發生在學校控制的設備。'},
 car:{q:'換個情境：一模一樣的汽車，學校公務車和老師開自己的車上班，怎麼分？',options:['公務車是學校直接排放（範疇一）；老師開車上班是學校間接造成的排放','兩個都是學校直接排放，因為都是汽車','老師的車不用算，因為不是學校的'],ok:'正確！要看「誰的車、做什麼用」，不是只看車子的外型。',retry:'再想想：學校自己的公務車算直接排放；老師為了上班開車，是學校間接造成的排放，表格也要統計。'},
 dispenser:{q:'換個情境：同一台飲水機，用電和用水怎麼分？',options:['用電算買來的電（範疇二）；用水算學校間接造成的排放','都算買來的電','飲水機不會冒煙，所以都不用算'],ok:'正確！同一台設備可以有不同活動，要分開登錄。',retry:'再想想：加熱、冰水用的是買來的電；自來水送到學校前，抽水和淨水也用了能源。'},
 reduction:{q:'換個情境：學校屋頂裝了太陽能板，它在碳盤查裡是什麼？',options:['是減碳：自己發電、自己用，就能少買電','是排放源：它也是一種發電設備','跟碳排放完全沒有關係'],ok:'正確！太陽能板和大樹是減碳、吸碳的幫手，不是排放源。',retry:'再想想：太陽能板發電時不燒燃料；學校自己用這些電，就能少買外面的電。'},
};
const quizFor:Record<Topic,keyof typeof quizzes>={combustion:'ac',fugitive:'ac',electricity:'ac',scope1:'ac',waste:'ac',mobile:'car',commute:'car',water:'dispenser',reduction:'reduction'};
export default function CarbonMatch(){
 const telemetry=useGameEvents('carbon');
 const [topic,setTopic]=useState<Topic>('combustion'),[game,setGame]=useState<Game>(()=>fresh(makeRound('combustion',37,true))),[started,setStarted]=useState(false),[tutorial,setTutorial]=useState(true),[spread,setSpread]=useState(false),[layout,setLayout]=useState(0),[sound,setSound]=useState(false),[hint,setHint]=useState(false),[hints,setHints]=useState(0),[quiz,setQuiz]=useState<number|null>(null),[restart,setRestart]=useState(false);
 const resultPanel=useRef<HTMLElement>(null);
 const bench=useRef<HTMLElement>(null),seed=useRef(37),current=useRef(game);current.current=game;
 const audio=useRef<AudioContext|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);audio.current?.close();},[]);
 function chime(good:boolean){if(!sound)return;try{const ac=audio.current??(audio.current=new AudioContext());void ac.resume();const gain=ac.createGain();gain.connect(ac.destination);gain.gain.setValueAtTime(.045,ac.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.24);for(const f of good?[523,659]:[220]){const o=ac.createOscillator();o.frequency.value=f;o.connect(gain);o.start();o.stop(ac.currentTime+.24);}}catch{/* Sound never blocks an answer. */}}
 function dispatch(a:Action){const next=act(current.current,a);if(next===current.current)return;const paired=next.history.length>current.current.history.length;current.current=next;setGame(next);if(paired){chime(next.kind==='correct');timer.current=setTimeout(()=>{setGame(s=>{const unlocked=act(s,{type:'unlock'});current.current=unlocked;return unlocked;});},next.kind==='correct'?650:1100);}}
 function start(chosen:Topic=topic,training=tutorial,same=false){telemetry.start({phase:'challenge',topic:chosen,tutorial:training});if(timer.current)clearTimeout(timer.current);if(!same)seed.current=(Date.now()+seed.current+17)>>>0;const next=fresh(makeRound(chosen,seed.current,training));current.current=next;setGame(next);setTopic(chosen);setTutorial(training);setStarted(true);setSpread(training);setLayout(0);setHint(false);setHints(0);setQuiz(null);setRestart(false);requestAnimationFrame(()=>bench.current?.scrollIntoView({block:'start',behavior:'instant'}));}
 const picked=game.round.pieces.find(p=>p.id===game.selected),selected=picked?itemByKey[picked.key]:null;
 const done=finished(game)&&!game.locked,count=found(game),tries=game.history.length,accuracy=tries?Math.round(count/tries*100):0;
 useEffect(()=>{if(done&&started)telemetry.complete({pairs:count,totalPairs:game.round.totalPairs,tries,accuracy,hints,toyErrors:game.history.filter(h=>h.kind==='toy').length,passed:true});},[done,started,telemetry,count,game,tries,accuracy,hints]);
 useEffect(()=>{if(done)resultPanel.current?.scrollIntoView({block:'start',behavior:'instant'});},[done]);
 const remaining=game.round.pieces.filter(p=>!game.removed.includes(p.id));
 const recorded=[...new Set(game.removed.map(id=>game.round.pieces.find(p=>p.id===id)!.key))];
 const topicInfo=topics[game.round.topic];
 return <main className={`cm-page ${started?'cm-playing':''}`}>
  <nav className="cm-top"><Link href="/package/1.2-III/">← 返回教案</Link><span>主題一 · 氣候科學</span><label><input type="checkbox" checked={sound} onChange={e=>setSound(e.target.checked)}/> 音效</label></nav>
  <header className="cm-header"><div><p className="cm-eyebrow">CAMPUS CARBON DETECTIVE</p><h1>校園碳排偵探<span>3D 配對任務</span></h1></div><span className="cm-header-note">找相同，更要找對排放來源。</span></header>
  {!started&&<section className="cm-intro"><div><span className="cm-kicker">學校要做碳盤查，換你來找！</span><h2>這一堆裡，<br/>哪些才是排放來源？</h2><p>設備與玩具混在一起。依照每局題目，點出相同的一對；<strong>玩具就算成對，也不能消除。</strong></p><ol><li><b>1</b>看本局排放主題</li><li><b>2</b>轉動、移開遮擋物</li><li><b>3</b>配對正確的排放活動</li></ol><small>完成配對代表登錄來源，不代表實際減碳。</small></div><div className="cm-setup"><p className="cm-eyebrow">選擇這次的任務</p><div className="cm-topic-groups">{topicGroups.map(g=><div key={g.label} className="cm-topic-group"><h3>{g.label}</h3><div className="cm-topic-options">{g.topics.map(t=><button key={t} aria-pressed={topic===t} onClick={()=>{setTopic(t);const next=fresh(makeRound(t,37,true));current.current=next;setGame(next);}}><span>{String(topicOrder.indexOf(t)+1).padStart(2,'0')}</span><strong>{topics[t].short}</strong><i>{topic===t?'✓':''}</i></button>)}</div></div>)}</div><p className="cm-topic-chosen"><b>{topics[topic].name}</b>{topics[topic].task}</p><label className="cm-training"><input type="checkbox" checked={tutorial} onChange={e=>setTutorial(e.target.checked)}/> 先練習：6 件物品、找 2 對 <span>正式局有 18 件</span></label><button className="cm-primary" onClick={()=>start()}>開始找一對 →</button></div></section>}
  <section className="cm-board" ref={bench} aria-label="配對工作桌">
   <div className="cm-mission"><div><p>{started?(tutorial?'練習局':'正式局'):'桌面預覽'} · {topicInfo.name}</p><h2>{topicInfo.task}</h2></div><div className="cm-count"><strong>{count}<i> / {game.round.totalPairs}</i></strong><span>對已登錄</span></div></div>
   <div className="cm-board-body"><div className="cm-playfield"><div className="cm-toolbar"><span>同物件 ＋ 同活動 ＋ 符合本題</span><div><button onClick={()=>setSpread(!spread)} aria-pressed={spread}>{spread?'疊回物件堆':'攤開看清楚'}</button><button onClick={()=>setLayout(n=>n+1)}>轉換擺放</button></div></div><Scene game={game} spread={spread} layout={layout} onPick={id=>started&&dispatch({type:'pick',id})}/>
   {!started&&<div className="cm-preview-note">先選任務，再按「開始找一對」</div>}
   {started&&<div className="cm-controls"><div className="cm-selection"><div className={selected?'filled':''}><small>① 已選物件</small><strong>{selected?.name||'先點一件物品'}</strong><span>{selected?.activity||'轉動桌面，查看物件的不同側面'}</span></div><b className="cm-pair-symbol">＋</b><div><small>② 找相同的一件</small><strong>{game.locked?'正在判定…':'再點第二件'}</strong><span>物件與活動都要相同</span></div></div><div className="cm-action-row"><button disabled={!selected||game.locked} onClick={()=>dispatch({type:'cancel'})}>取消選取</button><button disabled={!selected||game.locked} onClick={()=>dispatch({type:'park'})}>把選中物件移到旁邊 ↗</button><button onClick={()=>{if(!hint)setHints(n=>n+1);setHint(!hint);}} aria-expanded={hint}>觀察提示 {hint?'−':'＋'}</button></div><div className={`cm-feedback cm-${game.kind}`} role="status" aria-live="polite"><b>{game.kind==='correct'?'配對正確':game.kind==='neutral'?'下一步':'再想一下'}</b><span>{game.message}</span></div>{hint&&<p className="cm-hint">{topicInfo.clue} 無動力玩具留在桌上就好。選取後可閱讀物件的活動；看不清楚可按「攤開看清楚」。</p>}</div>}
   </div><aside className="cm-side"><div className="cm-side-head"><p className="cm-eyebrow">暫放區</p><h3>擋住了？先放旁邊。</h3><p>暫放不扣分、不算消除。仍可直接點它來配對。</p></div><div className="cm-parked">{game.parked.length?game.parked.map(id=>{const p=game.round.pieces.find(p=>p.id===id)!,i=itemByKey[p.key];return <div key={id}><button disabled={game.locked||done} aria-pressed={game.selected===id} onClick={()=>dispatch({type:'pick',id})}>{i.name}<small>物件 {id.slice(1)} · {i.activity}</small></button><button disabled={game.locked||done} onClick={()=>dispatch({type:'return',id})} aria-label={`放回物件 ${id.slice(1)}`}>↩</button></div>;}):<div className="cm-empty"><span>↗</span><p>選一件物品，再按<br/>「移到旁邊」</p></div>}</div><div className="cm-side-tip"><b>玩具可以留著</b><p>找完本局的 {game.round.totalPairs} 對目標就過關，<br/>不必清空桌面。</p></div></aside></div>
  </section>
  {started&&<>
   <details className="cm-object-list"><summary>物件清單 · 不方便點 3D 時，也能在這裡選取</summary><p>可直接配對桌上與暫放區的物件。此清單不會標示哪些是本局答案。</p><div>{remaining.map(p=>{const i=itemByKey[p.key];return <button key={p.id} disabled={game.locked||done} aria-pressed={game.selected===p.id} onClick={()=>dispatch({type:'pick',id:p.id})}><span>{p.id.slice(1).padStart(2,'0')}</span><div><b>{i.name}</b><small>{i.activity}{game.parked.includes(p.id)?' · 暫放中':''}</small></div></button>;})}</div></details>
   <div className="cm-session"><span>正確 {count} 對 · 已判定 {tries} 次 · 提示 {hints} 次</span><button onClick={()=>setRestart(true)}>換個主題／重新開始</button></div>
   {restart&&<div className="cm-restart"><p>本局配對進度將重設。要回到選題嗎？</p><button onClick={()=>setRestart(false)}>繼續這局</button><button onClick={()=>{if(timer.current)clearTimeout(timer.current);telemetry.abandon({pairs:count,totalPairs:game.round.totalPairs,tries,hints});setStarted(false);setGame(fresh(makeRound(topic,37,true)));setRestart(false);window.scrollTo({top:0,behavior:'smooth'});}}>回到選題</button></div>}
  </>}
  {done&&<section ref={resultPanel} className="cm-result" aria-label="本局結果"><p className="cm-eyebrow">任務完成</p><h2>{game.round.topic==='reduction'?'找到減碳與吸碳的幫手，也留下了其他物件。':'找到排放源，也留下了玩具。'}</h2><div className="cm-results-row"><div><strong>{count} / {game.round.totalPairs}</strong><span>目標完成</span></div><div><strong>{accuracy}%</strong><span>配對判斷正確率</span></div><div><strong>{game.history.filter(h=>h.kind==='toy').length}</strong><span>誤選玩具次數</span></div></div><p>這次完成的是來源辨識與登錄，不是減碳量。思考時間不扣分。</p><div className="cm-records">{recorded.map(key=><div key={key}><b>{itemByKey[key].name}</b><span>{itemByKey[key].reason}</span></div>)}</div><details><summary>看看留下什麼，以及配錯的原因</summary><p>{[...new Set(remaining.map(p=>p.key))].map(key=>`${itemByKey[key].name}（${captions[itemByKey[key].category]}）`).join('、')}。</p><p>誤判其他類別 {game.history.filter(h=>h.kind==='category').length} 次；不同物件或活動 {game.history.filter(h=>h.kind==='different').length} 次{game.history.some(h=>h.kind==='exempt')?`；配對了不必計入的走路／腳踏車 ${game.history.filter(h=>h.kind==='exempt').length} 次`:''}。一般玩具不是本局的運作排放活動，不代表生命週期零碳。</p></details><div className="cm-quiz"><b>{quizzes[quizFor[game.round.topic]].q}</b><div>{quizzes[quizFor[game.round.topic]].options.map((text,i)=><button key={text} aria-pressed={quiz===i} onClick={()=>setQuiz(i)}>{text}</button>)}</div>{quiz!==null&&<p role="status">{quiz===0?quizzes[quizFor[game.round.topic]].ok:quizzes[quizFor[game.round.topic]].retry}</p>}</div><div className="cm-result-actions"><button className="cm-primary" onClick={()=>start(game.round.topic,false)}>{tutorial?'進入正式局・18 件物品':'同主題，再找一局'} →</button><button onClick={()=>start(topicOrder[(topicOrder.indexOf(game.round.topic)+1)%topicOrder.length],false)}>換下一個主題・{topics[topicOrder[(topicOrder.indexOf(game.round.topic)+1)%topicOrder.length]].short} →</button></div></section>}
  <details className="cm-teacher"><summary>教師備註・盤查邊界與參考依據</summary><p>本遊戲延伸 1.2-III「溫室效應」的人為排放源辨識。題目假設設備屬學校自有或控制；範疇一包含固定燃燒、移動燃燒與逸散，範疇二只示範外購電力。員工通勤、外購水力、廢棄物處置在原表標為「其他間接溫室氣體排放」，畫面上一律稱「學校間接造成的排放」。冷氣及冰箱的冷媒種類依題目指定，不能推論所有產品都使用同一冷媒。</p><p>依《臺北市校園簡易碳盤查表格.xlsx》的 2-1 固定式排放源、2-2 移動式排放源、2-3 逸散性排放源、2-4 外購電力、2-5 員工通勤、2-6 外購水力、2-7 廢棄物處置與運輸、3-1 再生能源、3-2 樹木碳匯編寫；用電、用水設備模型是外購電力、外購水力項目的教學情境。除草機依 2-2 列為移動燃燒（2-1 另將肩背式除草機列為固定式，兩者都屬範疇一）。走路、騎腳踏車通勤依 2-5 註4 不必統計。加分關的太陽能、風力發電是減碳，樹木與灌木是碳匯，都不是排放源；自發自用的再生能源已反映在外購電力減少（3-1 註1）。玩具為無動力干擾物，不代表生命週期零排放。遊戲不計算 CO₂e、不引用舊年度係數、不作正式碳盤查。逸散氣體不一定肉眼可見。</p><p><a href="https://ghgprotocol.org/calculation-tools-faq" target="_blank" rel="noreferrer">GHG Protocol 分類說明 ↗</a> · 每局物件與位置可變；正確率為正確配對次數除以配對判定次數。取消、轉動、攤開及暫放都不計錯誤。</p><p>配對清單只存在本次頁面，重新整理會重設；不蒐集學生姓名。同意使用統計時，會傳送每局完成情形與結果摘要；不傳送文字回答。</p></details>
 </main>;
}
